package com.expense.expensemanagement.exception.modal;

public enum ErrorCode {
	AUTHENTICATION, JWT_TOKEN_EXPIRED, JWT_TOKEN_INVLID, USER_CREATION_FAILED, NEW_PASSWORD_REQUIRED, MISSING_FIELD
	, SERVER_ERROR, DUPLICATE_FIELD, NO_ELEMENT, WS_NOTIFICATION_REFRESH, INSUFFICIENT_AMOUNT;
}